import { Injectable } from '@angular/core';
import { IProduct } from './product.model';
import { Http, Response } from '@angular/http';
import 'rxjs/add/operator/map';
import { Observable } from 'rxjs/Rx';

@Injectable()
export class ProductService {

   private products: IProduct[] = [
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Legos", price: 20.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "four",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "iPad", price: 299.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "two",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "iPhone", price: 450.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "ten",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Pop the Pig Game", price: 4.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "nine",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Chuckle Ball Crazy Motorized Bouncing Action Ball", price: 5.99, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "five",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Disney Jr. Doc McStuffins Toy Hospital Care Cart", price: 50.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "seven",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "PS4", price: 199.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Xbox One S", price: 299.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "four",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Connect 4 game", price: 5.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "one",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "NERF N-Strike Elite HyperFire Blaster", price: 7.50, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "six",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Zoomer kitty - interactive cat", price: 50.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Barbie Dreamhouse", price: 35.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Legos", price: 20.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "four",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "iPad", price: 299.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "two",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "iPhone", price: 450.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "ten",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Pop the Pig Game", price: 4.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "nine",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Chuckle Ball Crazy Motorized Bouncing Action Ball", price: 5.99, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "five",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Disney Jr. Doc McStuffins Toy Hospital Care Cart", price: 50.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "seven",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "PS4", price: 199.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Xbox One S", price: 299.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "four",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Connect 4 game", price: 5.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "one",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "NERF N-Strike Elite HyperFire Blaster", price: 7.50, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "six",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Zoomer kitty - interactive cat", price: 50.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Barbie Dreamhouse", price: 35.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Legos", price: 20.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "four",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "iPad", price: 299.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "two",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "iPhone", price: 450.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "ten",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Pop the Pig Game", price: 4.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "nine",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Chuckle Ball Crazy Motorized Bouncing Action Ball", price: 5.99, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "five",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Disney Jr. Doc McStuffins Toy Hospital Care Cart", price: 50.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "seven",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "PS4", price: 199.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Xbox One S", price: 299.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "four",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Connect 4 game", price: 5.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "one",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "NERF N-Strike Elite HyperFire Blaster", price: 7.50, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "six",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Zoomer kitty - interactive cat", price: 50.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Barbie Dreamhouse", price: 35.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Legos", price: 20.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "four",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "iPad", price: 299.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "two",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "iPhone", price: 450.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "ten",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Pop the Pig Game", price: 4.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "nine",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Chuckle Ball Crazy Motorized Bouncing Action Ball", price: 5.99, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "five",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Disney Jr. Doc McStuffins Toy Hospital Care Cart", price: 50.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "seven",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "PS4", price: 199.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Xbox One S", price: 299.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "four",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Connect 4 game", price: 5.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "one",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "NERF N-Strike Elite HyperFire Blaster", price: 7.50, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "six",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Zoomer kitty - interactive cat", price: 50.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Barbie Dreamhouse", price: 35.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Legos", price: 20.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "four",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "iPad", price: 299.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "two",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "iPhone", price: 450.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "ten",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Pop the Pig Game", price: 4.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "nine",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Chuckle Ball Crazy Motorized Bouncing Action Ball", price: 5.99, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "five",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Disney Jr. Doc McStuffins Toy Hospital Care Cart", price: 50.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "seven",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "PS4", price: 199.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Xbox One S", price: 299.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "four",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Connect 4 game", price: 5.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "one",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "NERF N-Strike Elite HyperFire Blaster", price: 7.50, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "six",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Zoomer kitty - interactive cat", price: 50.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Barbie Dreamhouse", price: 35.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Legos", price: 20.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "four",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "iPad", price: 299.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "two",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "iPhone", price: 450.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "ten",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Pop the Pig Game", price: 4.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "nine",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Chuckle Ball Crazy Motorized Bouncing Action Ball", price: 5.99, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "five",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Disney Jr. Doc McStuffins Toy Hospital Care Cart", price: 50.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "seven",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "PS4", price: 199.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Xbox One S", price: 299.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "four",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Connect 4 game", price: 5.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "one",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "NERF N-Strike Elite HyperFire Blaster", price: 7.50, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "six",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Zoomer kitty - interactive cat", price: 50.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Barbie Dreamhouse", price: 35.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Legos", price: 20.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "four",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "iPad", price: 299.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "two",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "iPhone", price: 450.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "ten",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Pop the Pig Game", price: 4.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "nine",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Chuckle Ball Crazy Motorized Bouncing Action Ball", price: 5.99, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "five",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Disney Jr. Doc McStuffins Toy Hospital Care Cart", price: 50.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "seven",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "PS4", price: 199.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Xbox One S", price: 299.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "four",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Connect 4 game", price: 5.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "one",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "NERF N-Strike Elite HyperFire Blaster", price: 7.50, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "six",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Zoomer kitty - interactive cat", price: 50.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Barbie Dreamhouse", price: 35.00, isInCart: false},{ img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Legos", price: 20.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "four",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "iPad", price: 299.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "two",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "iPhone", price: 450.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "ten",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Pop the Pig Game", price: 4.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "nine",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Chuckle Ball Crazy Motorized Bouncing Action Ball", price: 5.99, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "five",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Disney Jr. Doc McStuffins Toy Hospital Care Cart", price: 50.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "seven",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "PS4", price: 199.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Xbox One S", price: 299.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "four",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Connect 4 game", price: 5.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "one",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "NERF N-Strike Elite HyperFire Blaster", price: 7.50, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "six",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Zoomer kitty - interactive cat", price: 50.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Barbie Dreamhouse", price: 35.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Legos", price: 20.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "four",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "iPad", price: 299.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "two",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "iPhone", price: 450.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "ten",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Pop the Pig Game", price: 4.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "nine",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Chuckle Ball Crazy Motorized Bouncing Action Ball", price: 5.99, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "five",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Disney Jr. Doc McStuffins Toy Hospital Care Cart", price: 50.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "seven",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "PS4", price: 199.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Xbox One S", price: 299.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "four",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Connect 4 game", price: 5.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "one",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "NERF N-Strike Elite HyperFire Blaster", price: 7.50, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "six",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Zoomer kitty - interactive cat", price: 50.00, isInCart: false},
    { img: "http://lorempixel.com/75/75/technics", age: "three",  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, purus in tempus sollicitudin, dui justo egestas mauris, ac mollis lacus sapien eu nulla. Sed aliquet ipsum turpis, id sodales ligula egestas quis. Nunc nec nisi ipsum. Morbi mattis elementum odio quis bibendum. Mauris vel augue viverra, lacinia nisi ut, sagittis neque. Etiam et mauris at eros facilisis posuere eu a eros. Duis ultricies facilisis semper. Suspendisse ultrices in mi a eleifend. ", name: "Barbie Dreamhouse", price: 35.00, isInCart: false}
  ]
  getProducts(): Observable<IProduct[]> {
    return this._http.get(this.apiUrl + "/product").map(this.extractData).catch(this.handleError);
  }

  filterProducts(ageFilter: any) : Observable<IProduct[]> {
    if (ageFilter.length == 0){
      return this._http.get(this.apiUrl + "/product").map(this.extractData).catch(this.handleError);
    }
    let filter = {
      ageFilter: ageFilter
    };
    return this._http.post(this.apiUrl + "/filter-products", filter).map(this.extractData).catch(this.handleError);
  }

  getAgeCounts(key: string): Observable<any> {
    let age = {
      age: key
    };
    return this._http.post(this.apiUrl + "/filter-counts", age).map((res: Response) => res.json()).catch(this.handleError)
  }
  
  addProduct(product: IProduct) {
    return this._http.post(this.apiUrl + "/product", product).map(this.extractData).catch(this.handleError);
  }

   private apiUrl: string = "http://localhost:3000/api";

  private extractData(res: Response) {
      let body = res.json();
      console.log(body);
      return {
          success: body.success,
          products: body.products || {}
       };
    }

private handleError (error: Response | any) {
    // In a real world app, we might use a remote logging infrastructure
    let errMsg: string;
    if (error instanceof Response) {
      const body = error.json() || '';
      if (body != ''){
        errMsg = body.message;
      } else {
        errMsg = body;
      }
    } else {
      errMsg = error.message ? error.message : error.toString();
    }
    console.error(errMsg);
    return Observable.throw(errMsg);
  }
  constructor(private _http: Http) { }
}
